
import { SignIn, SignInButton, SignOutButton } from "@clerk/clerk-react";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useUser } from "@clerk/clerk-react";

const Home: NextPage = () => {

    const user =  useUser();
  
  
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

          <div>   { !user.isSignedIn &&  <SignInButton/>}    </div> 
          <div>   { !!user.isSignedIn &&  <SignOutButton/>}    </div>

          
        
        <SignIn path="/sign-in" routing="path"signUpUrl="/signup" />

  
    </>
  );
};

export default Home;

