
import { SignIn, SignInButton, SignOutButton } from "@clerk/clerk-react";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useUser } from "@clerk/clerk-react";

const Home: NextPage = () => {

    const user =  useUser();
  
  
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <img
            className="mx-auto h-auto w-auto"
            src="https://cdn.discordapp.com/attachments/384545098949459969/1110744392765026475/logo.png"
            alt="Your Company"
          />

      <div className="flex justify-center rounded-auto text-sm font-semibold leading-6 py-2.5">
        {!user.isSignedIn && <SignInButton />}
      </div>

      <div className="flex auto justify-center rounded-auto text-sm font-semibold leading-6 py-2.5">
               {!!user.isSignedIn && <SignOutButton />}
        </div>
        
        <SignIn path="/sign-in" routing="path"signUpUrl="/signup" />

  
    </>

  );
};

export default Home;

